# Default initial positions for simple_arm's ros2_control fake system

initial_positions:
  base_to_link1_joint: 0
  elbow_joint: 0
  shoulder_joint: 0
  wrist_pitch_joint: 0
  wrist_roll_joint: 0
  wrist_yaw_joint: 0