controller_manager:
  ros__parameters:
    update_rate: 100  

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      []
    command_interfaces:
      []
    state_interfaces:
      []
    allow_nonzero_velocity_at_trajectory_end: true